Repository eitrtechnologies/idem-azurerm, pull requests merged in 2020-05, with the labels that each got.

#56 Add VM Present Diffs
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
  idem_provider_azurerm/states/azurerm/compute/virtual_machine.py
Labels: Enhancement

#65 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#70 Rename Azurerm Directories
  tests/integration/exec/azurerm/__init__.py
  tests/integration/exec/azurerm/resource/__init__.py
  tests/integration/exec/azurerm/resource/test_group.py
  tests/integration/states/azurerm/__init__.py
  tests/integration/states/azurerm/resource/__init__.py
  tests/integration/states/azurerm/resource/test_group.py
  tests/unit/exec/azurerm/__init__.py
  tests/unit/exec/azurerm/resource/__init__.py
  tests/unit/exec/azurerm/resource/test_group.py
Labels: Bug

#73 add initial pr template
  .github/pull_request_template.md
Labels: Documentation

#74 add contributing guide
  .github/CONTRIBUTING.md
Labels: Documentation

#84 Fixes decode of unicode chars in error
  requirements.txt
Labels: Bug Squasher
