Repository eitrtechnologies/idem-azurerm, pull requests merged in 2020-04, with the labels that each got.

#20 Keys Feature Addition
  idem_provider_azurerm/exec/azurerm/keyvault/key.py
  idem_provider_azurerm/exec/azurerm/keyvault/vault.py
  idem_provider_azurerm/exec/utils/azurerm.py
  idem_provider_azurerm/states/azurerm/keyvault/key.py
  idem_provider_azurerm/states/azurerm/keyvault/vault.py
Labels: Enhancement, Security

#13 Log Analytics Workspace
  idem_provider_azurerm/exec/azurerm/log_analytics/workspace.py
  idem_provider_azurerm/exec/utils/azurerm.py
  idem_provider_azurerm/states/azurerm/log_analytics/workspace.py
Labels: Enhancement, Security

#27 Absent State Module Kwargs
  idem_provider_azurerm/states/azurerm/compute/availability_set.py
  idem_provider_azurerm/states/azurerm/compute/virtual_machine.py
  idem_provider_azurerm/states/azurerm/dns/record_set.py
  idem_provider_azurerm/states/azurerm/dns/zone.py
  idem_provider_azurerm/states/azurerm/keyvault/key.py
  idem_provider_azurerm/states/azurerm/keyvault/vault.py
  idem_provider_azurerm/states/azurerm/monitor/diagnostic_setting.py
  idem_provider_azurerm/states/azurerm/network/load_balancer.py
  idem_provider_azurerm/states/azurerm/network/local_network_gateway.py
  idem_provider_azurerm/states/azurerm/network/network_interface.py
  idem_provider_azurerm/states/azurerm/network/network_security_group.py
  idem_provider_azurerm/states/azurerm/network/public_ip_address.py
  idem_provider_azurerm/states/azurerm/network/route.py
  idem_provider_azurerm/states/azurerm/network/virtual_network.py
  idem_provider_azurerm/states/azurerm/network/virtual_network_gateway.py
  idem_provider_azurerm/states/azurerm/network/virtual_network_peering.py
  idem_provider_azurerm/states/azurerm/redis/operations.py
  idem_provider_azurerm/states/azurerm/resource/group.py
  idem_provider_azurerm/states/azurerm/resource/management_lock.py
  idem_provider_azurerm/states/azurerm/resource/policy.py
  idem_provider_azurerm/states/azurerm/storage/account.py
  idem_provider_azurerm/states/azurerm/storage/container.py
Labels: Bug Squasher, Enhancement

#19 Management Groups
  idem_provider_azurerm/exec/azurerm/managementgroup/operations.py
  idem_provider_azurerm/states/azurerm/managementgroup/operations.py
Labels: Enhancement, Security

#29 Added list_ Module Aliases
  idem_provider_azurerm/exec/azurerm/compute/availability_set.py
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
  idem_provider_azurerm/exec/azurerm/dns/zone.py
  idem_provider_azurerm/exec/azurerm/keyvault/key.py
  idem_provider_azurerm/exec/azurerm/keyvault/vault.py
  idem_provider_azurerm/exec/azurerm/monitor/diagnostic_setting.py
  idem_provider_azurerm/exec/azurerm/monitor/log_profile.py
  idem_provider_azurerm/exec/azurerm/network/load_balancer.py
  idem_provider_azurerm/exec/azurerm/network/local_network_gateway.py
  idem_provider_azurerm/exec/azurerm/network/network_interface.py
  idem_provider_azurerm/exec/azurerm/network/network_security_group.py
  idem_provider_azurerm/exec/azurerm/network/public_ip_address.py
  idem_provider_azurerm/exec/azurerm/network/virtual_network.py
  idem_provider_azurerm/exec/azurerm/network/virtual_network_gateway.py
  idem_provider_azurerm/exec/azurerm/network/virtual_network_peerings.py
  idem_provider_azurerm/exec/azurerm/redis/operations.py
  idem_provider_azurerm/exec/azurerm/resource/deployment.py
  idem_provider_azurerm/exec/azurerm/resource/group.py
  idem_provider_azurerm/exec/azurerm/resource/provider.py
  idem_provider_azurerm/exec/azurerm/resource/subscription.py
  idem_provider_azurerm/exec/azurerm/resource/tenant.py
  idem_provider_azurerm/exec/azurerm/storage/account.py
  idem_provider_azurerm/exec/azurerm/storage/container.py
  idem_provider_azurerm/exec/azurerm/storage/sku.py
  idem_provider_azurerm/exec/azurerm/storage/usage.py
Labels: Enhancement

#35 Virtual Machine Extension Execution Modules
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine_extension.py
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine_extension_image.py
Labels: Enhancement, Security

#25 PostgreSQL 1/3
  idem_provider_azurerm/exec/azurerm/postgresql/check_name_availability.py
  idem_provider_azurerm/exec/azurerm/postgresql/configuration.py
  idem_provider_azurerm/exec/azurerm/postgresql/database.py
  idem_provider_azurerm/exec/azurerm/postgresql/firewall_rule.py
  idem_provider_azurerm/exec/azurerm/postgresql/operations.py
  idem_provider_azurerm/exec/azurerm/postgresql/server.py
  idem_provider_azurerm/exec/utils/azurerm.py
  idem_provider_azurerm/states/azurerm/postgresql/configuration.py
  idem_provider_azurerm/states/azurerm/postgresql/database.py
  idem_provider_azurerm/states/azurerm/postgresql/firewall_rule.py
  idem_provider_azurerm/states/azurerm/postgresql/server.py
Labels: Enhancement

#39 VM Extension Update
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine_extension.py
Labels: Bug Squasher

#26 PostgreSQL 2/3
  idem_provider_azurerm/exec/azurerm/postgresql/log_files.py
  idem_provider_azurerm/exec/azurerm/postgresql/server_security_alert_policy.py
  idem_provider_azurerm/exec/azurerm/postgresql/virtual_network_rule.py
  idem_provider_azurerm/states/azurerm/postgresql/server_security_alert_policy.py
  idem_provider_azurerm/states/azurerm/postgresql/virtual_network_rule.py
Labels: Enhancement

#41 Updated VM Extensions
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine_extension.py
Labels: Bug Squasher

#40 README
  README.md
Labels: Documentation

#42 Fix policy salt import
  idem_provider_azurerm/states/azurerm/resource/policy.py
Labels: Bug Squasher

#10 Encrypted Disk Functionality
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
Labels: Enhancement, Security

#47 VM exec module parity w/ Salt-Cloud
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
Labels: Documentation, Enhancement

#49 Fixes VM diagnostic profiles
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
Labels: Bug Squasher

#50 fixing missing windows param use
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
Labels: Bug Squasher

#54 Fixes disc encryption KeyError handling
  idem_provider_azurerm/exec/azurerm/compute/virtual_machine.py
Labels: Bug Squasher
