Repository eitrtechnologies/idem-azurerm, pull requests merged in 2020-08, with the labels that each got.

#142 Added missing waits and pollers for LROs
  idem_azurerm/exec/azurerm/keyvault/key.py
  idem_azurerm/exec/azurerm/keyvault/vault.py
  idem_azurerm/exec/azurerm/log_analytics/workspace.py
  idem_azurerm/exec/azurerm/managementgroup/operations.py
  idem_azurerm/exec/azurerm/network/virtual_network_gateway.py
  idem_azurerm/exec/azurerm/redis/operations.py
  idem_azurerm/exec/azurerm/storage/account.py
  idem_azurerm/states/azurerm/network/virtual_network_gateway.py
  idem_azurerm/states/azurerm/redis/operations.py
  tests/integration/states/azurerm/redis/test_redis_operations.py
Labels: Bug Squasher, Enhancement

#143 Add container instances
  docs/ref/exec/all/containerinstance/container.rst
  docs/ref/exec/all/containerinstance/group.rst
  docs/ref/exec/all/containerinstance/index.rst
  docs/ref/exec/all/index.rst
  docs/ref/states/all/containerinstance/group.rst
  docs/ref/states/all/containerinstance/index.rst
  docs/ref/states/all/index.rst
  idem_azurerm/exec/azurerm/containerinstance/container.py
  idem_azurerm/exec/azurerm/containerinstance/group.py
  idem_azurerm/exec/azurerm/utils.py
  idem_azurerm/states/azurerm/containerinstance/group.py
  requirements.txt
  tests/integration/states/azurerm/containerinstance/__init__.py
  tests/integration/states/azurerm/containerinstance/test_group.py
Labels: Enhancement

#144 Add network profile
  docs/ref/exec/all/network/index.rst
  docs/ref/exec/all/network/network_profile.rst
  docs/ref/states/all/network/index.rst
  docs/ref/states/all/network/network_profile.rst
  idem_azurerm/exec/azurerm/network/network_profile.py
  idem_azurerm/states/azurerm/network/network_profile.py
  tests/integration/states/azurerm/network/test_network_profile.py
Labels: Enhancement

#145 Azure Function Apps
  docs/ref/exec/all/application_insights/component.rst
  docs/ref/exec/all/application_insights/index.rst
  docs/ref/exec/all/index.rst
  docs/ref/exec/all/web/app.rst
  docs/ref/exec/all/web/app_service_plan.rst
  docs/ref/exec/all/web/index.rst
  docs/ref/states/all/index.rst
  docs/ref/states/all/web/function_app.rst
  docs/ref/states/all/web/index.rst
  idem_azurerm/exec/azurerm/application_insights/component.py
  idem_azurerm/exec/azurerm/storage/container.py
  idem_azurerm/exec/azurerm/utils.py
  idem_azurerm/exec/azurerm/web/app.py
  idem_azurerm/exec/azurerm/web/app_service_plan.py
  idem_azurerm/states/azurerm/web/function_app.py
  requirements.txt
  tests/integration/states/azurerm/web/test_function_app.py
Labels: Enhancement

#170 Bump idem
  requirements-test.txt
  requirements.txt
  tests/integration/conftest.py
  tests/integration/states/azurerm/containerinstance/test_group.py
  tests/integration/states/azurerm/containerregistry/test_registry.py
  tests/integration/states/azurerm/containerregistry/test_task.py
  tests/integration/states/azurerm/containerregistry/test_webhook.py
  tests/integration/states/azurerm/network/test_network_profile.py
Labels: Enhancement

#173 Function App Quickstart Guide
  docs/topics/functionsquickstart.rst
Labels: Documentation

#185 Authorization Bump
  idem_azurerm/exec/azurerm/authorization/permission.py
  idem_azurerm/exec/azurerm/authorization/provider.py
  idem_azurerm/exec/azurerm/authorization/role.py
  requirements.txt
Labels: Version Bump

#174 Monitor Bump
  idem_azurerm/exec/azurerm/monitor/diagnostic_setting.py
  idem_azurerm/states/azurerm/monitor/diagnostic_setting.py
  requirements.txt
Labels: Version Bump

#176 Management Group Bump
  requirements.txt
Labels: Version Bump

#175 DNS Bump
  idem_azurerm/exec/azurerm/dns/zone.py
  requirements.txt
Labels: Version Bump

#172 Log Analytics Bump
  idem_azurerm/exec/azurerm/log_analytics/workspace.py
  idem_azurerm/states/azurerm/log_analytics/workspace.py
  requirements.txt
  tests/integration/states/azurerm/log_analytics/test_workspace.py
Labels: Version Bump

#178 Bump Storage
  idem_azurerm/exec/azurerm/storage/account.py
  idem_azurerm/exec/azurerm/storage/container.py
  idem_azurerm/exec/azurerm/storage/usage.py
  idem_azurerm/states/azurerm/storage/account.py
  idem_azurerm/states/azurerm/storage/container.py
  requirements.txt
Labels: Enhancement, Version Bump

#182 Resource Bump
  idem_azurerm/exec/azurerm/resource/deployment.py
  idem_azurerm/exec/azurerm/resource/group.py
  idem_azurerm/exec/azurerm/resource/policy.py
  idem_azurerm/exec/azurerm/resource/provider.py
  idem_azurerm/exec/azurerm/resource/subscription.py
  idem_azurerm/exec/azurerm/resource/tenant.py
  idem_azurerm/states/azurerm/resource/group.py
  idem_azurerm/states/azurerm/resource/management_lock.py
  idem_azurerm/states/azurerm/resource/policy.py
  requirements.txt
  tests/integration/states/azurerm/resource/test_policy.py
Labels: Version Bump

#179 Bump Key Vault
  idem_azurerm/exec/azurerm/keyvault/key.py
  idem_azurerm/exec/azurerm/keyvault/vault.py
  idem_azurerm/states/azurerm/keyvault/key.py
  idem_azurerm/states/azurerm/keyvault/secret.py
  idem_azurerm/states/azurerm/keyvault/vault.py
  requirements.txt
  tests/integration/states/azurerm/keyvault/test_vault.py
Labels: Version Bump

#186 Monitor Bump Fixes
  idem_azurerm/exec/azurerm/monitor/diagnostic_setting.py
  idem_azurerm/states/azurerm/monitor/diagnostic_setting.py
Labels: Bug Squasher
